.DEFAULT_GOAL := help
PWD  =$(shell pwd)
UID  =$(shell id -u $${USER})
USER =$(shell echo $${USER})
GID  =$(shell id -g $${USER})
SID  =$(shell getent group sudo | cut -d: -f3 )

APP_NAME := tpi-buildtools
VERSION := v0.1.0

help:
	@echo "${UID} ${USER} ${GID} ${SUDO}"
	@echo "If this thing hits 88 MPH, you are gonna see some really cool stuff."
	@echo ""	
	@echo "Please make sure you have docker installed before starting!"
	@echo ""
	@echo "Docker Targets:"
	@echo "   image      Create the docker image complete with the build tools. "
	@echo "   debug      Runs the the docker image and puts you in bash for debug. "
	@echo "   firmware   Executes the full build instructions resulting in the latest firmware. "
	@echo ""
	@echo ""
	@echo "Utility Targets:"
	@echo "  clean       Cleans up all the stuff generated by this Makefile."
	@echo "  help        This message"

.PHONY: image
image:
	@echo '##################################'
	@echo '### Creating the docker image! ###'
	@echo '##################################'
	@echo ''
	@docker build \
		--build-arg USER=${USER}     \
		--build-arg UID=${UID}       \
		--label "version=${VERSION}" \
		-t ${APP_NAME}:${VERSION}    \
		. 

.PHONY: debug
debug:
	@docker run                              \
		-v ${PWD}:/opt/tpi                   \
		-v /etc/passwd:/etc/passwd:ro        \
		-v /etc/group:/etc/group:ro          \
		-u ${UID}:${GID}                     \
		--rm                                 \
		-it  								 \
		--entrypoint /bin/bash               \
		${APP_NAME}:${VERSION}

.PHONY: firmware
firmware:
	@docker run                              \
		-v ${PWD}:/opt/tpi                   \
		-v /etc/passwd:/etc/passwd:ro        \
		-v /etc/group:/etc/group:ro          \
		-u ${UID}:${GID}                     \
		--rm                                 \
		${APP_NAME}:${VERSION}               \
		./mkfw.sh 1.0.0
